
iNSERT INTO SEDESOL.C_TIPO_COLABORADOR (CSC_TIPO_COLABORADOR, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_COLABORADOR.NEXTVAL, 'Tipo Colaborador 1 ');
iNSERT INTO SEDESOL.C_TIPO_COLABORADOR (CSC_TIPO_COLABORADOR, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_COLABORADOR.NEXTVAL, 'Tipo Colaborador 2 ');
iNSERT INTO SEDESOL.C_TIPO_COLABORADOR (CSC_TIPO_COLABORADOR, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_COLABORADOR.NEXTVAL, 'Tipo Colaborador 3 ');

INSERT INTO SEDESOL.C_UBICACION_GEOGRAFICA(CSC_UBICACION_GEOGRAFICA,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_UBICACION_GEOGRAFICA.NEXTVAL, 'Ubicacion 1 ');
INSERT INTO SEDESOL.C_UBICACION_GEOGRAFICA(CSC_UBICACION_GEOGRAFICA,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_UBICACION_GEOGRAFICA.NEXTVAL, 'Ubicacion 2 ');
INSERT INTO SEDESOL.C_UBICACION_GEOGRAFICA(CSC_UBICACION_GEOGRAFICA,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_UBICACION_GEOGRAFICA.NEXTVAL, 'Ubicacion 3 ');


INSERT INTO SEDESOL.C_NOMBRE_COLABORADOR(CSC_NOMBRE_COLABORADOR, CHR_DESCRIPCION)   VALUES (SEDESOL.SEQ_CSC_NOMBRE_COLABORADOR.NEXTVAL, 'Nombre Colaborador 1 ');
INSERT INTO SEDESOL.C_NOMBRE_COLABORADOR(CSC_NOMBRE_COLABORADOR, CHR_DESCRIPCION)   VALUES (SEDESOL.SEQ_CSC_NOMBRE_COLABORADOR.NEXTVAL, 'Nombre Colaborador 2 ');
INSERT INTO SEDESOL.C_NOMBRE_COLABORADOR(CSC_NOMBRE_COLABORADOR, CHR_DESCRIPCION)   VALUES (SEDESOL.SEQ_CSC_NOMBRE_COLABORADOR.NEXTVAL, 'Nombre Colaborador 3 ');


iNSERT INTO SEDESOL.C_COLABORADOR_SISI (CSC_COLABORADOR_SISI, CSC_TIPO_COLABORADOR_FK, CSC_NOMBRE_COLABORADOR_FK, CSC_UBICACION_GEOGRAFICA_FK) VALUES(SEDESOL.SEQ_CSC_COLABORADOR_SISI.NEXTVAL,1,1,1);
iNSERT INTO SEDESOL.C_COLABORADOR_SISI (CSC_COLABORADOR_SISI, CSC_TIPO_COLABORADOR_FK, CSC_NOMBRE_COLABORADOR_FK, CSC_UBICACION_GEOGRAFICA_FK) VALUES(SEDESOL.SEQ_CSC_COLABORADOR_SISI.NEXTVAL,2,2,2);
iNSERT INTO SEDESOL.C_COLABORADOR_SISI (CSC_COLABORADOR_SISI, CSC_TIPO_COLABORADOR_FK, CSC_NOMBRE_COLABORADOR_FK, CSC_UBICACION_GEOGRAFICA_FK) VALUES(SEDESOL.SEQ_CSC_COLABORADOR_SISI.NEXTVAL,2,2,2);
  

iNSERT INTO SEDESOL.C_TIPO_CONVENIO (CSC_TIPO_CONVENIO, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_CONVENIO.NEXTVAL, 'Tipo Convenio 1');
iNSERT INTO SEDESOL.C_TIPO_CONVENIO (CSC_TIPO_CONVENIO, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_CONVENIO.NEXTVAL, 'Tipo Convenio 2');
iNSERT INTO SEDESOL.C_TIPO_CONVENIO (CSC_TIPO_CONVENIO, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_CONVENIO.NEXTVAL, 'Tipo Convenio 3');


iNSERT INTO SEDESOL.C_ESTATUS_CONVENIO (CSC_ESTATUS, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_ESTATUS.NEXTVAL, 'Estatus 1');
iNSERT INTO SEDESOL.C_ESTATUS_CONVENIO (CSC_ESTATUS, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_ESTATUS.NEXTVAL, 'Estatus 2');
iNSERT INTO SEDESOL.C_ESTATUS_CONVENIO (CSC_ESTATUS, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_ESTATUS.NEXTVAL, 'Estatus 3');


--Desaparecio CHR_NOMBRE_AUTORIZO, CHR_NOMBRE_APROBO
--INSERT INTO SEDESOL.VIGENCIA_CONVENIO (CSC_VIGENCIA_CONVENIO, FCH_INICIAL, FCH_FINAL, CHR_NOMBRE_AUTORIZO, CHR_NOMBRE_APROBO) VALUES(SEDESOL.SEQ_CSC_VIGENCIA_CONVENIO.NEXTVAL,to_date('23-JAN-17','DD-MON-RR'),to_date('26-JAN-17','DD-MON-RR'),'Pancho','Pantera');
--INSERT INTO SEDESOL.VIGENCIA_CONVENIO (CSC_VIGENCIA_CONVENIO, FCH_INICIAL, FCH_FINAL, CHR_NOMBRE_AUTORIZO, CHR_NOMBRE_APROBO) VALUES(SEDESOL.SEQ_CSC_VIGENCIA_CONVENIO.NEXTVAL,to_date('23-JAN-17','DD-MON-RR'),to_date('26-JAN-17','DD-MON-RR'),'Pedro','Picapiedra');

INSERT INTO SEDESOL.VIGENCIA_CONVENIO (CSC_VIGENCIA_CONVENIO, FCH_INICIAL, FCH_FINAL) VALUES(SEDESOL.SEQ_CSC_VIGENCIA_CONVENIO.NEXTVAL,to_date('23-JAN-17','DD-MON-RR'),to_date('26-JAN-17','DD-MON-RR'));
INSERT INTO SEDESOL.VIGENCIA_CONVENIO (CSC_VIGENCIA_CONVENIO, FCH_INICIAL, FCH_FINAL) VALUES(SEDESOL.SEQ_CSC_VIGENCIA_CONVENIO.NEXTVAL,to_date('23-JAN-17','DD-MON-RR'),to_date('26-JAN-17','DD-MON-RR'));




-- Titular Convenio CHR_EMAIL   esta mal el tamanio.
INSERT INTO SEDESOL.TITULAR_CONVENIO(CSC_TITULAR_CONVENIO,CHR_NOMBRE,CHR_CARGO,CHR_TELEFONO,CHR_EXTENSION,CHR_EMAIL) VALUES (SEDESOL.SEQ_CSC_TITULAR_CONVENIO.NEXTVAL, 'Daniel Sierra', 'CEO', '5537475053','44', 'doswald@gmail.com');


INSERT INTO SEDESOL.REPRESENTANTE_SEDESOL(CSC_REPRESENTANTE_SEDESOL, CHR_NOMBRE, CHR_CARGO ) VALUES (SEDESOL.SEQ_CSC_REPRESENTANTE_SEDESOL.NEXTVAL,'Ruben Alvarado','Consultor');

-- Error al insertar FK en CSC_TITULAR_CONVENIO_FK
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO1',1,1,to_date('23-JAN-17','DD-MON-RR'),1,3,1,1);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO2',1,1,to_date('23-JAN-17','DD-MON-RR'),1,3,1,1);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO3',2,1,to_date('23-JAN-17','DD-MON-RR'),1,3,1,2);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO4',2,1,to_date('27-JAN-17','DD-MON-RR'),1,3,1,2);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO5',2,2,to_date('27-JAN-17','DD-MON-RR'),2,3,1,2);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO6',3,2,to_date('10-JAN-17','DD-MON-RR'),2,3,1,2);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO7',3,2,to_date('10-JAN-17','DD-MON-RR'),2,3,1,3);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO8',3,2,to_date('10-JAN-17','DD-MON-RR'),2,3,1,3);


--Error en Tama;o de campos CHR_DESCRIPCION
--INSERT INTO SEDESOL.C_TIPO_DOCUMENTO(CSC_TIPO_DOCUMENTO,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_DOCUMENTO.NEXTVAL,'Addendum') ;
--INSERT INTO SEDESOL.C_TIPO_DOCUMENTO(CSC_TIPO_DOCUMENTO,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_DOCUMENTO.NEXTVAL,'Convenio Modificatorio') ;
--INSERT INTO SEDESOL.C_TIPO_DOCUMENTO(CSC_TIPO_DOCUMENTO,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_DOCUMENTO.NEXTVAL,'Terminación Anticipada') ;


INSERT INTO SEDESOL.C_TIPO_DOCUMENTO(CSC_TIPO_DOCUMENTO,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_DOCUMENTO.NEXTVAL,'Addendum') ;
INSERT INTO SEDESOL.C_TIPO_DOCUMENTO(CSC_TIPO_DOCUMENTO,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_DOCUMENTO.NEXTVAL,'Modificatorio') ;
INSERT INTO SEDESOL.C_TIPO_DOCUMENTO(CSC_TIPO_DOCUMENTO,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_DOCUMENTO.NEXTVAL,'Anticipada') ;


--Revisar Secuencias para CSC_CONVENIO_FK
INSERT INTO SEDESOL.CONVENIO_DOCUMENTOS (CSC_CONVENIO_DOC, CHR_NUMERO_FOLIO_DOC, CHR_OBSERVACION_DOC, FCH_DOCUMENTO, CSC_TIPO_DOCUMENTO_FK, CSC_CONVENIO_FK, BLOB_CONVENIO_DOCUMENTO ) 
  VALUES (SEDESOL.SEQ_CSC_CONVENIO_DOC.NEXTVAL, 'DOCUMENTO 1' , 'OBSERVACION 1' , to_date('23-JAN-17','DD-MON-RR'),1,17,null);
  
  
