/*Datos de prueba Convenio */
iNSERT INTO SEDESOL.C_TIPO_COLABORADOR (CSC_TIPO_COLABORADOR, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_COLABORADOR.NEXTVAL, 'Tipo Colaborador 1 ');
iNSERT INTO SEDESOL.C_TIPO_COLABORADOR (CSC_TIPO_COLABORADOR, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_COLABORADOR.NEXTVAL, 'Tipo Colaborador 2 ');
iNSERT INTO SEDESOL.C_TIPO_COLABORADOR (CSC_TIPO_COLABORADOR, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_COLABORADOR.NEXTVAL, 'Tipo Colaborador 3 ');

INSERT INTO SEDESOL.C_UBICACION_GEOGRAFICA(CSC_UBICACION_GEOGRAFICA,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_UBICACION_GEOGRAFICA.NEXTVAL, 'Ubicacion 1 ');
INSERT INTO SEDESOL.C_UBICACION_GEOGRAFICA(CSC_UBICACION_GEOGRAFICA,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_UBICACION_GEOGRAFICA.NEXTVAL, 'Ubicacion 2 ');
INSERT INTO SEDESOL.C_UBICACION_GEOGRAFICA(CSC_UBICACION_GEOGRAFICA,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_UBICACION_GEOGRAFICA.NEXTVAL, 'Ubicacion 3 ');


INSERT INTO SEDESOL.C_NOMBRE_COLABORADOR(CSC_NOMBRE_COLABORADOR, CHR_DESCRIPCION)   VALUES (SEDESOL.SEQ_CSC_NOMBRE_COLABORADOR.NEXTVAL, 'Nombre Colaborador 1 ');
INSERT INTO SEDESOL.C_NOMBRE_COLABORADOR(CSC_NOMBRE_COLABORADOR, CHR_DESCRIPCION)   VALUES (SEDESOL.SEQ_CSC_NOMBRE_COLABORADOR.NEXTVAL, 'Nombre Colaborador 2 ');
INSERT INTO SEDESOL.C_NOMBRE_COLABORADOR(CSC_NOMBRE_COLABORADOR, CHR_DESCRIPCION)   VALUES (SEDESOL.SEQ_CSC_NOMBRE_COLABORADOR.NEXTVAL, 'Nombre Colaborador 3 ');

iNSERT INTO SEDESOL.C_COLABORADOR_SISI (CSC_COLABORADOR_SISI, CSC_TIPO_COLABORADOR_FK, CSC_NOMBRE_COLABORADOR_FK, CSC_UBICACION_GEOGRAFICA_FK) VALUES(SEDESOL.SEQ_CSC_COLABORADOR_SISI.NEXTVAL,1,1,1);
iNSERT INTO SEDESOL.C_COLABORADOR_SISI (CSC_COLABORADOR_SISI, CSC_TIPO_COLABORADOR_FK, CSC_NOMBRE_COLABORADOR_FK, CSC_UBICACION_GEOGRAFICA_FK) VALUES(SEDESOL.SEQ_CSC_COLABORADOR_SISI.NEXTVAL,2,2,2);
iNSERT INTO SEDESOL.C_COLABORADOR_SISI (CSC_COLABORADOR_SISI, CSC_TIPO_COLABORADOR_FK, CSC_NOMBRE_COLABORADOR_FK, CSC_UBICACION_GEOGRAFICA_FK) VALUES(SEDESOL.SEQ_CSC_COLABORADOR_SISI.NEXTVAL,2,2,2);
  

iNSERT INTO SEDESOL.C_TIPO_CONVENIO (CSC_TIPO_CONVENIO, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_CONVENIO.NEXTVAL, 'Tipo Convenio 1');
iNSERT INTO SEDESOL.C_TIPO_CONVENIO (CSC_TIPO_CONVENIO, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_CONVENIO.NEXTVAL, 'Tipo Convenio 2');
iNSERT INTO SEDESOL.C_TIPO_CONVENIO (CSC_TIPO_CONVENIO, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_CONVENIO.NEXTVAL, 'Tipo Convenio 3');


iNSERT INTO SEDESOL.C_ESTATUS_CONVENIO (CSC_ESTATUS, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_ESTATUS.NEXTVAL, 'Estatus 1');
iNSERT INTO SEDESOL.C_ESTATUS_CONVENIO (CSC_ESTATUS, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_ESTATUS.NEXTVAL, 'Estatus 2');
iNSERT INTO SEDESOL.C_ESTATUS_CONVENIO (CSC_ESTATUS, CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_ESTATUS.NEXTVAL, 'Estatus 3');


INSERT INTO SEDESOL.VIGENCIA_CONVENIO (CSC_VIGENCIA_CONVENIO, FCH_INICIAL, FCH_FINAL) VALUES(SEDESOL.SEQ_CSC_VIGENCIA_CONVENIO.NEXTVAL,to_date('23-01-17','DD-MM-YY'),to_date('26-01-17','DD-MM-YY'));
INSERT INTO SEDESOL.VIGENCIA_CONVENIO (CSC_VIGENCIA_CONVENIO, FCH_INICIAL, FCH_FINAL) VALUES(SEDESOL.SEQ_CSC_VIGENCIA_CONVENIO.NEXTVAL,to_date('23-01-17','DD-MM-YY'),to_date('26-01-17','DD-MM-YY'));

INSERT INTO SEDESOL.TITULAR_CONVENIO(CSC_TITULAR_CONVENIO,CHR_NOMBRE,CHR_CARGO,CHR_TELEFONO,CHR_EXTENSION,CHR_EMAIL) VALUES (SEDESOL.SEQ_CSC_TITULAR_CONVENIO.NEXTVAL, 'Daniel Sierra', 'CEO', '5537475053','44', 'doswald@gmail.com');


INSERT INTO SEDESOL.REPRESENTANTE_SEDESOL(CSC_REPRESENTANTE_SEDESOL, CHR_NOMBRE, CHR_CARGO ) VALUES (SEDESOL.SEQ_CSC_REPRESENTANTE_SEDESOL.NEXTVAL,'Ruben Alvarado','Consultor');

Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO1',1,1,to_date('23-01-17','DD-MM-YY'),1,3,1,1);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO2',1,1,to_date('23-01-17','DD-MM-YY'),1,3,1,1);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO3',2,1,to_date('23-01-17','DD-MM-YY'),1,3,1,2);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO4',2,1,to_date('27-01-17','DD-MM-YY'),1,3,1,2);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO5',2,2,to_date('27-01-17','DD-MM-YY'),2,3,1,2);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO6',3,2,to_date('10-01-17','DD-MM-YY'),2,3,1,2);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO7',3,2,to_date('10-01-17','DD-MM-YY'),2,3,1,3);
Insert into CONVENIO (CSC_CONVENIO,CHR_FOLIO_CONVENIO,CSC_COLABORADOR_SISI_FK,CSC_VIGENCIA_CONVENIO_FK,FCH_CONVENIO,CSC_TIPO_CONVENIO_FK,CSC_TITULAR_CONVENIO_FK,CSC_REPRESENTANTE_SEDESOL_FK,CSC_ESTATUS_FK) values (SEDESOL.SEQ_CSC_CONVENIO.NEXTVAL,'FOLIO8',3,2,to_date('10-01-17','DD-MM-YY'),2,3,1,3);

INSERT INTO SEDESOL.C_TIPO_DOCUMENTO(CSC_TIPO_DOCUMENTO,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_DOCUMENTO.NEXTVAL,'Addendum') ;
INSERT INTO SEDESOL.C_TIPO_DOCUMENTO(CSC_TIPO_DOCUMENTO,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_DOCUMENTO.NEXTVAL,'Modificatorio') ;
INSERT INTO SEDESOL.C_TIPO_DOCUMENTO(CSC_TIPO_DOCUMENTO,CHR_DESCRIPCION) VALUES (SEDESOL.SEQ_CSC_TIPO_DOCUMENTO.NEXTVAL,'Terminación Anticipada') ;

INSERT INTO SEDESOL.CONVENIO_DOCUMENTOS (CSC_CONVENIO_DOC, CHR_NUMERO_FOLIO_DOC, CHR_OBSERVACION_DOC, FCH_DOCUMENTO, CSC_TIPO_DOCUMENTO_FK, CSC_CONVENIO_FK, BLOB_CONVENIO_DOCUMENTO ) 
  VALUES (SEDESOL.SEQ_CSC_CONVENIO_DOC.NEXTVAL, 'DOCUMENTO 1' , 'OBSERVACION 1' , to_date('23-01-17','DD-MM-YY'),1,17,null);

/*Datos registro de adhesion*/

INSERT INTO  DATOS_CONTACTO_TITULAR (CSC_DATOS_CONTACTO_TITULAR, TUA_CARGO, TUA_TEL, TUA_CORREO, TUA_EXT, TUA_NOMBRE, TUA_PRIMER_AP, TUA_SEGUNDO_AP) values (SEDESOL.SEQ_CSC_DATOS_CONTACTO_TITULAR.NEXTVAL, 'Dependiente', '5548541232', 'lalolanda@hidalgo.gob.mx', '56', 'Lalo', 'Landa', 'Lopez');

INSERT INTO  RESPONSABLE_PROGRAMA_SOCIAL (CSC_RESPONSABLE_PROGRAMA_SOC, RP_NOMBRE, RP_CARGO, RP_TEL, RP_CORREO, RP_EXT, RP_PRIMER_AP, RP_SEGUNDO_AP) values (SEDESOL.SEQ_CSC_RESPONSABLE_PRO_SOC.NEXTVAL, 'Pepe','Colaborador', '5548541232', 'lalolanda@hidalgo.gob.mx', '56', 'LePew', 'Lopez');


INSERT INTO  REGISTRO_ADHESION (CSC_REGISTRO_ADHESION, CSC_DATOS_CONTACTO_TITULAR_FK, SN_ENTIDAD_NORMADA, FCH_REGISTRO_ADHESION, RA_FOLIO, SN_OPERA_PROGRAMAS_SOCIALES, INT_NUMERO_PROGRAMAS_SOCIALES, CSC_CONVENIO_FK, CHR_OBSERVACIONES_REG_ADH) values (SEDESOL.SEQ_CSC_REGISTRO_ADHESION.NEXTVAL, 1, 1, to_date('19-02-17','DD-MM-YY'), 'Ra/Folio/01', 1, 2, 26, 'Todo ok!' );


INSERT INTO  PROGRAMAS_SOCIALES (CSC_PROGRAMAS_SOCIALES, CHR_CLAVE_PRESUPUESTAL_PRO, CHR_NOMBRE_PROGRAMA, CSC_REGISTRO_ADHESION_FK) values (SEDESOL.SEQ_CSC_PROGRAMAS_SOCIALES.NEXTVAL, 'CLAVE PRESUP 1', ' PROG 1', 1);
INSERT INTO  PROGRAMAS_SOCIALES (CSC_PROGRAMAS_SOCIALES, CHR_CLAVE_PRESUPUESTAL_PRO, CHR_NOMBRE_PROGRAMA, CSC_REGISTRO_ADHESION_FK) values (SEDESOL.SEQ_CSC_PROGRAMAS_SOCIALES.NEXTVAL, 'CLAVE PRESUP 2', ' PROG 2', 1);
INSERT INTO  PROGRAMAS_SOCIALES (CSC_PROGRAMAS_SOCIALES, CHR_CLAVE_PRESUPUESTAL_PRO, CHR_NOMBRE_PROGRAMA, CSC_REGISTRO_ADHESION_FK) values (SEDESOL.SEQ_CSC_PROGRAMAS_SOCIALES.NEXTVAL, 'CLAVE PRESUP 3', ' PROG 3', 1);
INSERT INTO  PROGRAMAS_SOCIALES (CSC_PROGRAMAS_SOCIALES, CHR_CLAVE_PRESUPUESTAL_PRO, CHR_NOMBRE_PROGRAMA, CSC_REGISTRO_ADHESION_FK) values (SEDESOL.SEQ_CSC_PROGRAMAS_SOCIALES.NEXTVAL, 'CLAVE PRESUP 4', ' PROG 4', 1);
INSERT INTO  PROGRAMAS_SOCIALES (CSC_PROGRAMAS_SOCIALES, CHR_CLAVE_PRESUPUESTAL_PRO, CHR_NOMBRE_PROGRAMA, CSC_REGISTRO_ADHESION_FK) values (SEDESOL.SEQ_CSC_PROGRAMAS_SOCIALES.NEXTVAL, 'CLAVE PRESUP 5', ' PROG 5', 1);

INSERT INTO  PROGRAMAS_SOC_RESPONSABLE_PRO (CSC_PROGRAMA_RES_PRO, CSC_RESPONSABLE_PRO_SOC_FK, CSC_PROGRAMAS_SOCIALES_FK) values (SEDESOL.SEQ_CSC_PROGRAMA_RES_PRO.NEXTVAL, 1, 2);

INSERT INTO  PROGRAMAS_SOC_RESPONSABLE_PRO (CSC_PROGRAMA_RES_PRO, CSC_RESPONSABLE_PRO_SOC_FK, CSC_PROGRAMAS_SOCIALES_FK) values (SEDESOL.SEQ_CSC_PROGRAMA_RES_PRO.NEXTVAL, 1, 3);


INSERT INTO  C_PARTICIPACION_UA (CSC_PART_UA, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_PART_UA.NEXTVAL, 'PART UA 1');
INSERT INTO  C_PARTICIPACION_UA (CSC_PART_UA, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_PART_UA.NEXTVAL, 'PART UA 2');
INSERT INTO  C_PARTICIPACION_UA (CSC_PART_UA, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_PART_UA.NEXTVAL, 'PART UA 3');
INSERT INTO  C_PARTICIPACION_UA (CSC_PART_UA, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_PART_UA.NEXTVAL, 'PART UA 4');


INSERT INTO  C_TIPO_PARTICIPACION (CSC_TIPO_PARTICIPACION, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_PARTICIPANTES.NEXTVAL, 'Recursos financieros');
INSERT INTO  C_TIPO_PARTICIPACION (CSC_TIPO_PARTICIPACION, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_PARTICIPANTES.NEXTVAL, 'Operación (incluye recursos humanos y materiales)');
INSERT INTO  C_TIPO_PARTICIPACION (CSC_TIPO_PARTICIPACION, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_PARTICIPANTES.NEXTVAL, 'Ambos');


INSERT INTO  C_PARTICIPANTES (CSC_PARTICIPANTES, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_TIPO_PARTICIPACION.NEXTVAL, 'Programa');
INSERT INTO  C_PARTICIPANTES (CSC_PARTICIPANTES, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_TIPO_PARTICIPACION.NEXTVAL, 'Fondo');
INSERT INTO  C_PARTICIPANTES (CSC_PARTICIPANTES, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_TIPO_PARTICIPACION.NEXTVAL, 'Instituciones o dependencias');
INSERT INTO  C_PARTICIPANTES (CSC_PARTICIPANTES, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_TIPO_PARTICIPACION.NEXTVAL, 'Personas beneficiarias, grupos y/o asociaciones');

INSERT INTO  C_ORDEN_GOBIERNO (CSC_ORDEN_GOBIERNO, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_ORDEN_GOBIERNO.NEXTVAL, 'Federal');
INSERT INTO  C_ORDEN_GOBIERNO (CSC_ORDEN_GOBIERNO, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_ORDEN_GOBIERNO.NEXTVAL, 'Estatal');
INSERT INTO  C_ORDEN_GOBIERNO (CSC_ORDEN_GOBIERNO, CHR_DESCRIPCION) values (SEDESOL.SEQ_CSC_ORDEN_GOBIERNO.NEXTVAL, 'Municipal');


--INSERT INTO CUAPS(CSC_CUAPS, CUAPS_FOLIO, FH_LEVANTAMIENTO, CSC_PROGRAMA_FK,FH_FIN_LEVANTAMIENTO, CSC_REGISTRO_ADHESION_FK )  
--VALUES (SEDESOL.SEQ_CSC_CUAPS.NEXTVAL, 'CUAPS 1', to_date('23-JAN-17','DD-MON-RR'),   )
