

--select * from C_DERECHOS_SOCIALES;
INSERT INTO "SEDESOL"."C_DER_SOCIAL_BIE_ECO" (CSC_DER_SOCIAL, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_DER_SOCIAL.NEXTVAL, 'Educación', '1');
INSERT INTO "SEDESOL"."C_DER_SOCIAL_BIE_ECO" (CSC_DER_SOCIAL, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_DER_SOCIAL.NEXTVAL, 'Salud', '1');
INSERT INTO "SEDESOL"."C_DER_SOCIAL_BIE_ECO" (CSC_DER_SOCIAL, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_DER_SOCIAL.NEXTVAL, 'Alimentación', '1');
INSERT INTO "SEDESOL"."C_DER_SOCIAL_BIE_ECO" (CSC_DER_SOCIAL, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_DER_SOCIAL.NEXTVAL, 'Vivienda', '1');
INSERT INTO "SEDESOL"."C_DER_SOCIAL_BIE_ECO" (CSC_DER_SOCIAL, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_DER_SOCIAL.NEXTVAL, 'Medio Ambiente', '1');
INSERT INTO "SEDESOL"."C_DER_SOCIAL_BIE_ECO" (CSC_DER_SOCIAL, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_DER_SOCIAL.NEXTVAL, 'Trabajo', '1');
INSERT INTO "SEDESOL"."C_DER_SOCIAL_BIE_ECO" (CSC_DER_SOCIAL, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_DER_SOCIAL.NEXTVAL, 'Seguridad Social', '1');
INSERT INTO "SEDESOL"."C_DER_SOCIAL_BIE_ECO" (CSC_DER_SOCIAL, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_DER_SOCIAL.NEXTVAL, 'No Discriminación', '1');
INSERT INTO "SEDESOL"."C_DER_SOCIAL_BIE_ECO" (CSC_DER_SOCIAL, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.CSC_DER_SOCIAL.NEXTVAL, 'Bienestar Económico', '1');



Select * from C_CRITERIO_SELECCION_POBLACION;
Select * from C_PERIODICIDAD;
Select * from C_CARENCIAS_SOCIALES;
Select * from C_DESCRIPCION_FONDO;



-- Errores 
-- C_DESCRIPCION_FONDO             SN_ACTIVO
-- C_IDENTIFICADOR_EJECUTOR_FONDO  PRESUPUESTO_ASIGNADO_ENTIDAD  PRESUPUESTO_ASIGNADO_ENTIDAD_FK



Insert into SEDESOL.C_DESCRIPCION_FONDO (CSC_DESCRIPCION_FONDO,CHR_CVE_DEPENDENCIA_NACIONAL,CHR_NOMBRE_DEPENDENCIA_NACIONA,PRESUPUESTO_FONDO_NACIONAL,CHR_CONTRIBUCION_FONDO_NACIONA,CHR_PROPOSITO_FONDO_NACIONAL,CHR_POBLACION_OBJETIVO_FONDO,CHR_NOMBRE_FONDO,CHR_CLAVE_FONDO,SN_ACTIVO) values (1,'416','Direcci�n General de Programaci�n y Presupuesto A',8172311398,'Contribuir a construir un entorno digno que propicie el desarrollo a trav�s de la mejora en los servicios b�sicos, la calidad y espacios de la vivienda y la infraestructura social. mediante la reducci�n de los rezagos en materia de servicios b�sicos en la vivienda, calidad y espacios de la vivienda e infraestructura social de la poblaci�n que habita en las zonas de atenci�n prioritaria, en las localidades con los dos mayores grados de rezago social de cada municipio o que se encuentra en situaci�n de pobreza extrema','La poblaci�n que habita en las zonas de atenci�n prioritaria rurales, en los municipios con los dos mayores grados de rezago social de cada entidad o que se encuentra en situaci�n de pobreza extrema reducen los rezagos en infraestructura social b�sica relacionada con las carencias de servicios b�sicos en la vivienda, calidad y espacios de la vivienda e infraestructura social','La poblaci�n que habita en las zonas de atenci�n prioritaria rurales, en los municipios con los dos mayores grados de rezago social de cada entidad o que se encuentra en situaci�n de pobreza extrema ','Fondo para la Infraestructura Social de las Entidades (FISE)','F/FISE',1);
Insert into SEDESOL.C_DESCRIPCION_FONDO (CSC_DESCRIPCION_FONDO,CHR_CVE_DEPENDENCIA_NACIONAL,CHR_NOMBRE_DEPENDENCIA_NACIONA,PRESUPUESTO_FONDO_NACIONAL,CHR_CONTRIBUCION_FONDO_NACIONA,CHR_PROPOSITO_FONDO_NACIONAL,CHR_POBLACION_OBJETIVO_FONDO,CHR_NOMBRE_FONDO,CHR_CLAVE_FONDO,SN_ACTIVO) values (2,'416','Direcci�n General de Programaci�n y Presupuesto A',59247924900,'Contribuir a construir un entorno digno que propicie el desarrollo a trav�s de la mejora en los servicios b�sicos, la calidad y espacios de la vivienda y la infraestructura social. mediante la reducci�n de los rezagos en materia de servicios b�sicos en la vivienda, calidad y espacios de la vivienda e infraestructura social de la poblaci�n que habita en las zonas de atenci�n prioritaria, en las localidades con los dos mayores grados de rezago social de cada municipio o que se encuentra en situaci�n de pobreza extrema','La poblaci�n que habita en las zonas de atenci�n prioritaria urbanas, en las localidades con los dos mayores grados de rezago social de cada municipio o que se encuentra en situaci�n de pobreza extrema reducen los rezagos en infraestructura social b�sica relacionada con las carencias de servicios b�sicos en la vivienda, calidad y espacios de la vivienda e infraestructura social','La poblaci�n que habita en las zonas de atenci�n prioritaria urbanas, en las localidades con los dos mayores grados de rezago social de cada municipio o que se encuentra en situaci�n de pobreza extrema','Fondo para la Infraestructura Social Municipal y de las Demarcaciones Territoriales del Distrito Federal (FISMDF)','F/FISMDF',1);

Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (1,41204467,1,1,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (2,50237947,1,2,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (3,20257616,1,3,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (4,86157995,1,4,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (5,68982755,1,5,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (6,23418612,1,6,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (7,1364442461,1,7,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (8,158078298,1,8,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (9,111944033,1,9,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (10,116411161,1,10,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (11,291730646,1,11,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (12,679597892,1,12,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (13,248870704,1,13,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (14,197574882,1,14,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (15,556742852,1,15,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (16,341383159,1,16,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (17,81121503,1,17,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (18,81404589,1,18,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (19,97763080,1,19,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (20,790500811,1,20,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (21,648261174,1,21,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (22,81929999,1,22,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (23,87148413,1,23,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (24,253453891,1,24,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (25,105820556,1,25,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (26,73661138,1,26,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (27,165020193,1,27,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (28,108834516,1,28,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (29,79343838,1,29,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (30,845942806,1,30,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (31,188918354,1,31,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (32,113892589,1,32,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (33,298725660,2,1,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (34,364216918,2,2,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (35,146864414,2,3,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (36,624631410,2,4,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (37,500113722,2,5,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (38,169781122,2,6,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (39,9891985327,2,7,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (40,1146041879,2,8,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (41,811575977,2,9,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (42,843961934,2,10,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (43,2114999608,2,11,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (44,4926973890,2,12,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (45,1804272019,2,13,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (46,1432385677,2,14,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (47,4036294888,2,15,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (48,2474972231,2,16,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (49,588117668,2,17,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (50,590169989,2,18,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (51,708766383,2,19,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (52,5731001963,2,20,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (53,4699787799,2,21,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (54,593979136,2,22,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (55,631811782,2,23,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (56,1837499377,2,24,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (57,767181780,2,25,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (58,534031242,2,26,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (59,1196369488,2,27,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (60,789032492,2,28,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (61,575229892,2,29,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (62,6132947391,2,30,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (63,1369627253,2,31,1);
Insert into SEDESOL.C_IDENTIFICADOR_EJECUTOR_FONDO (CSC_IDENTIFICADOR_EJE_FON,PRESUPUESTO_ASIGNADO_ENTIDAD,CSC_DESCRIPCION_FONDO_FK,CVE_ENTIDAD,SN_ACTIVO) values (64,825702702,2,32,1);

Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (1,'ACCESO A LA ALIMENTACI�N',1,1);
Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (2,'ACCESO A LOS SERVICIOS DE SALUD',1,1);
Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (3,'CALIDAD Y ESPACIOS DE LA VIVIENDA',1,1);
Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (4,'SERVICIOS B�SICOS DE LA VIVIENDA',1,1);
Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (5,'APOYOS COMPLEMENTARIOS',1,1);
Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (6,'AGUA POTABLE',2,1);
Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (7,'ALCANTARILLADO',2,1);
Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (8,'DRENAJE Y LETRINAS',2,1);
Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (9,'URBANIZACI�N MUNICIPAL',2,1);
Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (10,'INFRAESTRUCTURA B�SICA DEL SECTOR SALUD',2,1);
Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (11,'INFRAESTRUCTURA B�SICA DEL SECTOR EDUCATIVO',2,1);
Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (12,'MEJORAMIENTO DE VIVIENDA',2,1);
Insert into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK,SN_ACTIVO) values (13,'MANTENIMIENTO DE INFRAESTRUCTURA',2,1);


Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (1,'COMEDORES COMUNITARIOS',1,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (2,'PREESCOLAR (COMEDORES ESCOLARES)',1,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (3,'PRIMARIA (COMEDORES ESCOLARES)',1,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (4,'SECUNDARIA (COMEDORES ESCOLARES)',1,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (5,'CENTROS DE SALUD O UNIDADES M�DICAS',2,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (6,'HOSPITALES',2,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (7,'CISTERNA',3,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (8,'CONEXI�N A LA RED DE DRENAJE O FOSA S�PTICA',3,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (9,'CUARTO PARA BA�O',3,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (10,'CUARTO PARA COCINA',3,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (11,'CUARTOS DORMITORIO',3,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (12,'MURO FIRME (QUE NO SEA CON MATERIALES DE: EMBARRO BAJAREQUE, CARRIZO, BAMB�, PALMA; L�MINA DE CART�N, MET�LICA O DE ASBESTO O MATERIAL DE DESECHO)',3,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (13,'PISO FIRME',3,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (14,'TECHO FIRME (NO MATERIAL DE DESECHO, NI L�MINA DE CART�N)',3,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (15,'TERRAPLENES PARA EL MEJORAMIENTO DE LA VIVIENDA',3,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (16,'DRENAJE PLUVIAL Y SANITARIO',4,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (17,'DRENAJE PLUVIAL Y SANITARIO',4,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (18,'ELECTRIFICACI�N',4,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (19,'ELECTRIFICACI�N NO CONVENCIONAL (ENERG�A E�LICA, AEROGENERADORES, ENERG�A SOLAR, PANELES, SOLAR FOTOVOLTAICA, SOLAR T�RMICA, ETC.)',4,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (20,'ESTUFAS ECOL�GICAS',4,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (21,'PLANTA POTABILIZADORA',4,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (22,'POZOS DE ABSORCI�N',4,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (23,'RED O SISTEMA DE AGUA POTABLE',4,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (24,'SANITARIOS CON BIODIGESTORES',4,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (25,'SANITARIOS SECOS/ LETRINAS',4,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (26,'ALUMBRADO P�BLICO',5,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (27,'CAMINOS / CARRETERAS EN LOS MUNICIPIOS Y LOCALIDADES CON ESCASAS V�AS DE COMUNICACI�N.',5,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (28,'CAMINOS RURALES',5,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (29,'PLANTA DE TRATAMIENTO DE AGUAS RESIDUALES',5,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (30,'PLANTA POTABILIZADORA',6,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (31,'C�RCAMO',6,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (32,'DEP�SITO O TANQUE DE AGUA POTABLE',6,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (33,'NORIAS',6,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (34,'OLLA/ COLECTOR DE CAPTACI�N DE AGUA PLUVIAL',6,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (35,'POZO ARTESIANO',6,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (36,'POZO PROFUNDO DE AGUA POTABLE',6,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (37,'RED O SISTEMA DE AGUA POTABLE',6,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (38,'RED DE ALCANTARILLADO',7,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (39,'L�NEAS DE CONDUCCI�N',7,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (40,'DRENAJE PLUVIAL',8,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (41,'DRENAJE SANITARIO',8,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (42,'PLANTA DE TRATAMIENTO DE AGUAS RESIDUALES',8,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (43,'POZOS DE ABSORCI�N',8,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (44,'TANQUES S�PTICOS CONECTADO A FOSA S�PTICA O DRENAJE',8,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (45,'CAMINOS RURALES',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (46,'COMEDORES COMUNITARIOS',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (47,'ALUMBRADO P�BLICO',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (48,'INFRAESTRUCTURA Y EQUIPAMIENTO P�BLICO PARA EL ACCESO Y EL APOYO DE LAS PERSONAS CON DISCAPACIDAD',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (49,'NIVELACI�N DE TIERRAS / RELLENO DE SOLARES',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (50,'ALBERGUES',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (51,'CALLES (ADOQU�N, ASFALTO, CONCRETO Y EMPEDRADO)',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (52,'ELECTRIFICACI�N DE POZOS',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (53,'GUARNICIONES Y BANQUETAS',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (54,'MUROS DE CONTENCI�N',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (55,'PAVIMENTACI�N',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (56,'REVESTIMIENTO',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (57,'SE�AL�TICA',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (58,'VADO',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (59,'CAMINOS / CARRETERAS',9,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (60,'CL�NICA DENTAL',10,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (61,'DISPENSARIO M�DICO',10,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (62,'CENTROS DE SALUD O UNIDADES M�DICAS',10,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (63,'HOSPITALES',10,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (64,'PREESCOLAR (COMEDORES ESCOLARES)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (65,'PRIMARIA (COMEDORES ESCOLARES)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (66,'SECUNDARIA(COMEDORES ESCOLARES)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (67,'PREESCOLAR (AULAS)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (68,'PREESCOLAR (DOTACI�N DE SERVICIOS B�SICOS: AGUA, ELECTRICIDAD, DRENAJE)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (69,'PREESCOLAR (SANITARIOS)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (70,'PREPARATORIA (AULAS)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (71,'PREPARATORIA (DOTACI�N DE SERVICIOS B�SICOS: AGUA, ELECTRICIDAD, DRENAJE)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (72,'PREPARATORIA (SANITARIOS)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (73,'PRIMARIA (AULAS)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (74,'PRIMARIA (DOTACI�N DE SERVICIOS B�SICOS: AGUA, ELECTRICIDAD, DRENAJE)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (75,'PRIMARIA (SANITARIOS)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (76,'SECUNDARIA (AULAS)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (77,'SECUNDARIA (DOTACI�N DE SERVICIOS B�SICOS: AGUA, ELECTRICIDAD, DRENAJE)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (78,'SECUNDARIA (SANITARIOS)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (79,'PREESCOLAR (BARDAS PERIMETRALES)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (80,'PREPARATORIA (BARDAS PERIMETRALES)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (81,'PRIMARIA (BARDAS PERIMETRALES)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (82,'SECUNDARIA (BARDAS PERIMETRALES)',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (83,'BIBLIOTECA',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (84,'TECHADOS EN �REAS DE IMPARTICI�N DE EDUCACI�N F�SICA',11,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (85,'TOMA DOMICILIARIA DENTRO DE LA VIVIENDA O TERRENO',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (86,'ELECTRIFICACI�N NO CONVENCIONAL (ENERG�A E�LICA, AEROGENERADORES, ENERG�A SOLAR, PANELES, SOLAR FOTOVOLTAICA, SOLAR T�RMICA, ETC.)',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (87,'ELECTRIFICACI�N',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (88,'CISTERNA',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (89,'CONEXI�N A LA RED DE DRENAJE O FOSA S�PTICA (DESCARGA DOMICILIARIA)',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (90,'CUARTO PARA BA�O',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (91,'CUARTO PARA COCINA',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (92,'CUARTOS DORMITORIO',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (93,'ESTUFAS ECOL�GICAS',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (94,'MURO FIRME (QUE NO SEA CON MATERIALES DE: EMBARRO BAJAREQUE, CARRIZO, BAMB�, PALMA; L�MINA DE CART�N, MET�LICA O DE ASBESTO O MATERIAL DE DESECHO)',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (95,'PISO FIRME',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (96,'SANITARIOS SECOS / LETRINAS',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (97,'TECHO FIRME (NO MATERIAL DE DESECHO, NI L�MINA DE CART�N)',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (98,'TERRAPLENES PARA EL MEJORAMIENTO DE LA VIVIENDA',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (99,'SANITARIOS CON BIODIGESTORES',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (100,'CALENTADORES SOLARES',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (101,'ELECTRIFICACI�N RURAL',12,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (102,'INFRAESTRUCTURA AGR�COLA: ABREVADEROS',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (103,'INFRAESTRUCTURA AGR�COLA: BORDOS',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (104,'INFRAESTRUCTURA AGR�COLA: CAMINO SACACOSECHAS',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (105,'INFRAESTRUCTURA AGR�COLA: CANALES',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (106,'INFRAESTRUCTURA AGR�COLA: DESPIEDRE',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (107,'INFRAESTRUCTURA AGR�COLA: HUERTOS COMUNITARIOS',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (108,'INFRAESTRUCTURA AGR�COLA: MAQUINARIA E IMPLEMENTOS COMUNITARIOS',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (109,'INFRAESTRUCTURA AGR�COLA: NIVELACI�N DE TIERRAS',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (110,'INFRAESTRUCTURA AGR�COLA: PRESAS',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (111,'INFRAESTRUCTURA AGR�COLA: SISTEMAS DE RIEGO TECNIFICADO',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (112,'INFRAESTRUCTURA AP�COLA: SALA DE EXTRACCI�N DE MIEL',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (113,'INFRAESTRUCTURA ARTESANAL: ESPACIO, MAQUINARIA Y EQUIPO ARTESANAL COMUNITARIOS',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (114,'INFRAESTRUCTURA FORESTAL: MAQUINARIA Y EQUIPO COMUNITARIO PARA EL MEJORAMIENTO DE SUELOS',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (115,'INFRAESTRUCTURA PECUARIA: ESPACIO, MAQUINARIA Y EQUIPO COMUNITARIO',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (116,'INFRAESTRUCTURA AGR�COLA: MECANIZACI�N DE TIERRA',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (117,'INFRAESTRUCTURA AP�COLA: SALA DE EXTRACCI�N DE MIEL',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (118,'INFRAESTRUCTURA  ARTESANAL: ESPACIO, MAQUINARIA Y EQUIPO ARTESANAL COMUNITARIOS',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (119,'INFRAESTRUCTURA FORESTAL: MAQUINARIA Y EQUIPO COMUNITARIO PARA EL MEJORAMIENTO DE SUELOS',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (120,'INFRAESTRUCTURA PECUARIA: ESPACIO, MAQUINARIA Y EQUIPO COMUNITARIO',13,1);
Insert into SEDESOL.C_TIPO_APOYO_VERTIENTE (CSC_TIPO_APOYO_VER,CHR_DESCRIPCION,CSC_VERTIENTES_FK,SN_ACTIVO) values (121,'INFRAESTRUCTURA Y EQUIPAMIENTO PARA EL ACCESO DE LAS PERSONAS CON DISCAPACIDAD',13,1);


--SELECT * FROM C_LISTADO_PADRON;
INSERT INTO "SEDESOL"."C_TIPO_PADRON" (CSC_LISTADO_PADRON, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_LISTADO_PADRON.NEXTVAL, 'Personas', '1');
INSERT INTO "SEDESOL"."C_TIPO_PADRON" (CSC_LISTADO_PADRON, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_LISTADO_PADRON.NEXTVAL, 'Poblaciones beneficiarias de obras de infraestructura o acciones comunitarias', '1');
INSERT INTO "SEDESOL"."C_TIPO_PADRON" (CSC_LISTADO_PADRON, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_LISTADO_PADRON.NEXTVAL, 'Actores sociales', '1');
INSERT INTO "SEDESOL"."C_TIPO_PADRON" (CSC_LISTADO_PADRON, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_LISTADO_PADRON.NEXTVAL, 'Otro', '1');

--select * from C_PERIODO_ACTUALIZA;
INSERT INTO "SEDESOL"."C_PERIODICIDAD" (CSC_PERIODO_ACTUALIZA, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_PERIODO_ACTUALIZA.NEXTVAL, 'Mensual', '1');
INSERT INTO "SEDESOL"."C_PERIODICIDAD" (CSC_PERIODO_ACTUALIZA, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_PERIODO_ACTUALIZA.NEXTVAL, 'Bimestral', '1');
INSERT INTO "SEDESOL"."C_PERIODICIDAD" (CSC_PERIODO_ACTUALIZA, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_PERIODO_ACTUALIZA.NEXTVAL, 'Trimestral', '1');
INSERT INTO "SEDESOL"."C_PERIODICIDAD" (CSC_PERIODO_ACTUALIZA, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_PERIODO_ACTUALIZA.NEXTVAL, 'Cuatrimestral', '1');
INSERT INTO "SEDESOL"."C_PERIODICIDAD" (CSC_PERIODO_ACTUALIZA, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_PERIODO_ACTUALIZA.NEXTVAL, 'Semestral', '1');
INSERT INTO "SEDESOL"."C_PERIODICIDAD" (CSC_PERIODO_ACTUALIZA, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_PERIODO_ACTUALIZA.NEXTVAL, 'Anual', '1');
INSERT INTO "SEDESOL"."C_PERIODICIDAD" (CSC_PERIODO_ACTUALIZA, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_PERIODO_ACTUALIZA.NEXTVAL, 'Otro', '1');


--SELECT * FROM C_CRITERIO_POBLACION;
INSERT INTO "SEDESOL"."C_CRITERIO_POBLACION" (CSC_CRITERIO_POBLACION, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_CRITERIO_POBLACION.NEXTVAL, 'Población en pobreza extrema', '1');
INSERT INTO "SEDESOL"."C_CRITERIO_POBLACION" (CSC_CRITERIO_POBLACION, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_CRITERIO_POBLACION.NEXTVAL, 'Zona de Atención prioritaria', '1');
INSERT INTO "SEDESOL"."C_CRITERIO_POBLACION" (CSC_CRITERIO_POBLACION, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_CRITERIO_POBLACION.NEXTVAL, 'Localidades con Alto y Muy alto grado de Rezago Social', '1');


--SELECT * FROM C_INCIDENCIA_PROYECTO;
INSERT INTO "SEDESOL"."C_INCIDENCIA_PROYECTO" (CSC_INCIDENCIA_PROYECTO, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_INCIDENCIA_PROYECTO.NEXTVAL, 'Directa', '1');
INSERT INTO "SEDESOL"."C_INCIDENCIA_PROYECTO" (CSC_INCIDENCIA_PROYECTO, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_INCIDENCIA_PROYECTO.NEXTVAL, 'Complementaria', '1');
INSERT INTO "SEDESOL"."C_INCIDENCIA_PROYECTO" (CSC_INCIDENCIA_PROYECTO, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_INCIDENCIA_PROYECTO.NEXTVAL, 'ESpecial', '1');






--select * from C_CARENCIAS_SOCIALES;


INSERT INTO "SEDESOL"."C_CARENCIAS_SOCIALES" (CSC_CARENCIAS_SOCIALES, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_CARENCIAS_SOCIALES.NEXTVAL, 'Acceo a la alimentación', '1');
INSERT INTO "SEDESOL"."C_CARENCIAS_SOCIALES" (CSC_CARENCIAS_SOCIALES, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_CARENCIAS_SOCIALES.NEXTVAL, 'Calidad y espacios en la vivienda', '1');
INSERT INTO "SEDESOL"."C_CARENCIAS_SOCIALES" (CSC_CARENCIAS_SOCIALES, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_CARENCIAS_SOCIALES.NEXTVAL, 'Servicios básicos en la vivienda', '1');
INSERT INTO "SEDESOL"."C_CARENCIAS_SOCIALES" (CSC_CARENCIAS_SOCIALES, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_CARENCIAS_SOCIALES.NEXTVAL, 'Acceso a los servicios de salud', '1');
INSERT INTO "SEDESOL"."C_CARENCIAS_SOCIALES" (CSC_CARENCIAS_SOCIALES, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_CARENCIAS_SOCIALES.NEXTVAL, 'Atención al rezago educativo', '1');
INSERT INTO "SEDESOL"."C_CARENCIAS_SOCIALES" (CSC_CARENCIAS_SOCIALES, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_CARENCIAS_SOCIALES.NEXTVAL, 'Acceso a la seguridad social', '1');
INSERT INTO "SEDESOL"."C_CARENCIAS_SOCIALES" (CSC_CARENCIAS_SOCIALES, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_CARENCIAS_SOCIALES.NEXTVAL, 'Ingreso por debajo de la línea de bienestar', '1');
INSERT INTO "SEDESOL"."C_CARENCIAS_SOCIALES" (CSC_CARENCIAS_SOCIALES, CHR_DESCRIPCION, SN_ACTIVO) VALUES (SEDESOL.SEQ_CSC_CARENCIAS_SOCIALES.NEXTVAL, 'Ingreso por debajo de la linea de bienestar Mínimo', '1');





INSERT INTO "SEDESOL"."C_INCIDENCIA" (CSC_INCIDENCIA_PROYECTO, CHR_DESCRIPCION, SN_ACTIVO) VALUES ('1', 'DIRECTA', '1');
INSERT INTO "C_INCIDENCIA" (CSC_INCIDENCIA_PROYECTO, CHR_DESCRIPCION, SN_ACTIVO) VALUES ('2', 'COMPLEMENTARIA', '1');
INSERT INTO "C_INCIDENCIA" (CSC_INCIDENCIA_PROYECTO, CHR_DESCRIPCION, SN_ACTIVO) VALUES ('3', 'ESPECIAL', '1');
--select * from C_INCIDENCIA;


--select * from C_DESCRIPCION_FONDO
INSERT INTO SEDESOL.C_DESCRIPCION_FONDO (CSC_DESCRIPCION_FONDO,CSC_FONDOS_ESPECIALES_FK,CHR_CVE_DEPENDENCIA_NACIONAL,CHR_NOMBRE_DEPENDENCIA_NACIONA,PRESUPUESTO_FONDO_NACIONAL,CHR_CONTRIBUCION_FONDO_NACIONA,CHR_PROPOSITO_FONDO_NACIONAL,CHR_POBLACION_OBJETIVO_FONDO,CHR_NOMBRE_FONDO,CHR_CLAVE_FONDO) values (SEDESOL.SEQ_CSC_DESCRIPCION_FONDO.NEXTVAL,1,'416','DirecciÃ³n General de ProgramaciÃ³n y Presupuesto A',8172311398,'Contribuir a construir un entorno digno que propicie el desarrollo a travÃ©s de la mejora en los servicios bÃ¡sicos, la calidad y espacios de la vivienda y la infraestructura social. mediante la reducciÃ³n de los rezagos en materia de servicios bÃ¡sicos en la vivienda, calidad y espacios de la vivienda e infraestructura social de la poblaciÃ³n que habita en las zonas de atenciÃ³n prioritaria, en las localidades con los dos mayores grados de rezago social de cada municipio o que se encuentra en situaciÃ³n de pobreza extrema','La poblaciÃ³n que habita en las zonas de atenciÃ³n prioritaria rurales, en los municipios con los dos mayores grados de rezago social de cada entidad o que se encuentra en situaciÃ³n de pobreza extrema reducen los rezagos en infraestructura social bÃ¡sica relacionada con las carencias de servicios bÃ¡sicos en la vivienda, calidad y espacios de la vivienda e infraestructura social','La poblaciÃ³n que habita en las zonas de atenciÃ³n prioritaria rurales, en los municipios con los dos mayores grados de rezago social de cada entidad o que se encuentra en situaciÃ³n de pobreza extrema ','Fondo para la Infraestructura Social de las Entidades (FISE) tabla descripcion fondo','F/FISE');
INSERT INTO SEDESOL.C_DESCRIPCION_FONDO (CSC_DESCRIPCION_FONDO,CSC_FONDOS_ESPECIALES_FK,CHR_CVE_DEPENDENCIA_NACIONAL,CHR_NOMBRE_DEPENDENCIA_NACIONA,PRESUPUESTO_FONDO_NACIONAL,CHR_CONTRIBUCION_FONDO_NACIONA,CHR_PROPOSITO_FONDO_NACIONAL,CHR_POBLACION_OBJETIVO_FONDO,CHR_NOMBRE_FONDO,CHR_CLAVE_FONDO) values (SEDESOL.SEQ_CSC_DESCRIPCION_FONDO.NEXTVAL,1,'416','DirecciÃ³n General de ProgramaciÃ³n y Presupuesto A',59247924900,'Contribuir a construir un entorno digno que propicie el desarrollo a travÃ©s de la mejora en los servicios bÃ¡sicos, la calidad y espacios de la vivienda y la infraestructura social. mediante la reducciÃ³n de los rezagos en materia de servicios bÃ¡sicos en la vivienda, calidad y espacios de la vivienda e infraestructura social de la poblaciÃ³n que habita en las zonas de atenciÃ³n prioritaria, en las localidades con los dos mayores grados de rezago social de cada municipio o que se encuentra en situaciÃ³n de pobreza extrema','La poblaciÃ³n que habita en las zonas de atenciÃ³n prioritaria urbanas, en las localidades con los dos mayores grados de rezago social de cada municipio o que se encuentra en situaciÃ³n de pobreza extrema reducen los rezagos en infraestructura social bÃ¡sica relacionada con las carencias de servicios bÃ¡sicos en la vivienda, calidad y espacios de la vivienda e infraestructura social','La poblaciÃ³n que habita en las zonas de atenciÃ³n prioritaria urbanas, en las localidades con los dos mayores grados de rezago social de cada municipio o que se encuentra en situaciÃ³n de pobreza extrema','Fondo para la Infraestructura Social Municipal y de las Demarcaciones Territoriales del Distrito Federal (FISMDF)','F/FISMDF');



--C_VERTIENTES
--select * from c_vertientes
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'ACCESO A LA ALIMENTACIÃ“N',1);
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'ACCESO A LOS SERVICIOS DE SALUD',1);
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'CALIDAD Y ESPACIOS DE LA VIVIENDA',1);
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'SERVICIOS BÃ?SICOS DE LA VIVIENDA',1);
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'APOYOS COMPLEMENTARIOS',1);
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'Agua potable',2);
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'Alcantarillado',2);
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'Drenaje y letrinas',2);
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'UrbanizaciÃ³n municipal',2);
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'Infraestructura bÃ¡sica del sector salud',2);
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'Infraestructura bÃ¡sica del sector educativo',2);
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'Mejoramiento de vivienda',2);
INSERT into SEDESOL.C_VERTIENTES (CSC_VERTIENTES,CHR_DESCRIPCION,CSC_DESCRIPCION_FONDO_FK) values (SEDESOL.SEQ_CSC_VERTIENTES.NEXTVAL,'Mantenimiento de infraestructura',2);


Insert into C_CONFIGURACION_FOCALIZACION (CSC_CONFIGURACION_FOC,NIVEL_1_DESCRIPCION,NIVEL_2_DESCRIPCION,NIVEL_3_DESCRIPCION,NIVEL_4_DESCRIPCION,RESUMEN_NARRATIVO,CODIFICACION_SINTAXIS,CSC_C_NIVEL_CERO_FK,NIVELES) values (1339,'Programa de Apoyo al Empleo de la Secretar�a de Trabajo y Previsi�n Social (STPS)','2015 y 2016','3. RECIBIR UN APOYO ESPEC�FICO DEL PROGRAMA','Apoyo econ�mico para traslado','Recibir el Apoyo econ�mico para traslado del Programa de Apoyo al Empleo de la Secretar�a de Trabajo y Previsi�n Social (STPS) en el a�o 2015 y 2016','IN_PAE15_ECON = 1 & IN_PAE16_ECON= 1',9,4);



--C_PADRON
--select * from c_padron

INSERT INTO SEDESOL.C_PADRON (CSC_PADRON,CHR_DESCRIPCION,SN_ACTIVO) values (SEDESOL.SEQ_CSC_PADRON.NEXTVAL,'Personas',1);
INSERT INTO SEDESOL.C_PADRON (CSC_PADRON,CHR_DESCRIPCION,SN_ACTIVO) values (SEDESOL.SEQ_CSC_PADRON.NEXTVAL,'Comunidades beneficiarias de obras, servicios o acciones beneficiarias',1);
INSERT INTO SEDESOL.C_PADRON (CSC_PADRON,CHR_DESCRIPCION,SN_ACTIVO) values (SEDESOL.SEQ_CSC_PADRON.NEXTVAL,'Actores Sociales',1);
INSERT INTO SEDESOL.C_PADRON (CSC_PADRON,CHR_DESCRIPCION,SN_ACTIVO) values (SEDESOL.SEQ_CSC_PADRON.NEXTVAL,'Otro ',1);




/**************************************+TABLAS EXISTENTES EN LA NUEVA BD (PC GABY)***********************/
/*
select * from C_IDENTIFICADOR_EJECUTOR_FONDO

select * from C_DER_SOCIAL_BIE_ECO

SELECT * FROM C_TEMATICA_BIENESTAR

SELECT * FROM C_ORDEN_DE_GOBIERNO

select * from C_CRITERIO_SELECCION_POBLACION    

select * from C_INCI_PROYECTO  

select * from C_DER_SOCIAL_BIE_ECO     

select * from C_CARENCIAS_SOCIALES

select * from C_DESCRIPCION_FONDO

select * from C_VERTIENTES

select * from TIPO_PADRON      
*/
