--------------------------------------------------------
-- Archivo creado  - martes-febrero-28-2017   
--------------------------------------------------------
DROP SEQUENCE "SEDESOL"."SEQ_CSC_AUDITORIA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_AUTORIZACION";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_C_NIVEL_CERO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CARACTERISTICAS";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CARACTERISTICAS_OPE";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CARENCIAS_SOCIALES";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_COLABORADOR_SISI";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_COMPARTICION_OTROS_PRO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_COMPONENTE_PROGRAMA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CON_FOCALIZACION";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CONFIGURACION_FOC";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CONSULTA_PRO_SER_SISI";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CONTACTO_ENL_TEC";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CONTACTO_ENLACE_TEC";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CONTRIBUCION_DER_SOC";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CONVENIO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CONVENIO_DOC";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CRITERIO_SELECCION";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CUANTIFICACION_POB";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_CUAPS";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_DATOS_ADM_BIE";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_DATOS_ADMINISTRATIVOS";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_DATOS_CONTACTO_ENLACE";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_DATOS_CONTACTO_TITULAR";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_DEPENDENCIA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_DEPENDENCIA_PROGRAMA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_DER_SOC_BIE_ECO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_DER_SOCIAL";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_DERECHOS_SOCIALES";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_DESCRIPCION_FONDO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_DETALLE_PRO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_DOCUMENTO_NORMATIVO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_ELA_AUT_PROYECTO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_ENLACE_PRO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_ENTIDAD";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_ENTIDAD_FEDERATIVA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_ESTATUS";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_ESTATUS_CUAPS";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_ESTATUS_RA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_EVALUACIONES";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_FOCALIZACION";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_FONDO_EJERCE_RECURSOS";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_FONDOS_ESP_REG_ADH";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_FONDOS_ESPECIALES";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_FORMATO_REG_ADM";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_FRECUENCIA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_GEORREFERENCIACION";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_GRUPO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_GRUPO_ROL";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_GRUPO_USUARIO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_IDENTIFICADOR_EJE_FON";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_INCI_PROYECTO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_INDICES";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_INFO_APORTA_SISI";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_INFO_INTE_ADM";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_INFORMACION_APO_SISI";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_INSUMOS_REGISTRO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_MATRIZ_FOCALIZACION";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_MATRIZ_GESTION";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_MENU";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_MIR";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_MUNICIPIO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_NOMBRE_COLABORADOR";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_NORMATIVIDAD_PRO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_OBJETIVOS_ESP";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_OBJETO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_ORDEN_DE_GOBIERNO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_ORDEN_GOBIERNO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PADRON";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PANTALLA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PART_UA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PARTICIPANTES";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PERIODICIDAD";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PROGRAMA_CON_PRO_SISI";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PROGRAMA_CUAPS";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PROGRAMA_INF_APO_SISI";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PROGRAMA_RES_PRO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PROGRAMAS_SOCIALES";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PROYECTOS_CAR";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PROYECTOS_DER_SOC";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_PROYECTOS_FONDOS";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_RECURSOS_FINANCIEROS";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_REGISTRO_ADHESION";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_REGISTRO_ADHESION_AUT";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_REGISTRO_VARIABLES";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_REGISTROS_ADM";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_REGISTROS_ADMIN";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_REPRESENTANTE_SEDESOL";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_RESPONSABLE_FONDO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_RESPONSABLE_PRO_SOC";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_ROL";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_ROL_MENU";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TEMATICA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TEMATICA_BIE";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TIPO_ADM";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TIPO_APOYO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TIPO_APOYO_DER";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TIPO_APOYO_PRO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TIPO_AUTORIZADOR";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TIPO_COLABORADOR";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TIPO_CONVENIO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TIPO_DOCUMENTO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TIPO_PADRON";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TIPO_PARTICIPACION";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_TITULAR_CONVENIO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_UA_SIN_PROGRAMA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_UBICACION_GEOGRAFICA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_UNIDAD_ADM";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_UNIDAD_ADMINISTRATIVA";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_USUARIO";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_USUARIO_ROL";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_VARIABLES_ADM";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_VERTIENTES";
DROP SEQUENCE "SEDESOL"."SEQ_CSC_VIGENCIA_CONVENIO";
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_AUDITORIA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_AUDITORIA"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_AUTORIZACION
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_AUTORIZACION"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_C_NIVEL_CERO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_C_NIVEL_CERO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CARACTERISTICAS
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CARACTERISTICAS"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CARACTERISTICAS_OPE
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CARACTERISTICAS_OPE"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CARENCIAS_SOCIALES
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CARENCIAS_SOCIALES"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_COLABORADOR_SISI
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_COLABORADOR_SISI"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_COMPARTICION_OTROS_PRO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_COMPARTICION_OTROS_PRO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_COMPONENTE_PROGRAMA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_COMPONENTE_PROGRAMA"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CON_FOCALIZACION
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CON_FOCALIZACION"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CONFIGURACION_FOC
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CONFIGURACION_FOC"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CONSULTA_PRO_SER_SISI
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CONSULTA_PRO_SER_SISI"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CONTACTO_ENL_TEC
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CONTACTO_ENL_TEC"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CONTACTO_ENLACE_TEC
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CONTACTO_ENLACE_TEC"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CONTRIBUCION_DER_SOC
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CONTRIBUCION_DER_SOC"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CONVENIO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CONVENIO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CONVENIO_DOC
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CONVENIO_DOC"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CRITERIO_SELECCION
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CRITERIO_SELECCION"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CUANTIFICACION_POB
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CUANTIFICACION_POB"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_CUAPS
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_CUAPS"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_DATOS_ADM_BIE
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_DATOS_ADM_BIE"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_DATOS_ADMINISTRATIVOS
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_DATOS_ADMINISTRATIVOS"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_DATOS_CONTACTO_ENLACE
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_DATOS_CONTACTO_ENLACE"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_DATOS_CONTACTO_TITULAR
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_DATOS_CONTACTO_TITULAR"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_DEPENDENCIA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_DEPENDENCIA"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_DEPENDENCIA_PROGRAMA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_DEPENDENCIA_PROGRAMA"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_DER_SOC_BIE_ECO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_DER_SOC_BIE_ECO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_DER_SOCIAL
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_DER_SOCIAL"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_DERECHOS_SOCIALES
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_DERECHOS_SOCIALES"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_DESCRIPCION_FONDO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_DESCRIPCION_FONDO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_DETALLE_PRO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_DETALLE_PRO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_DOCUMENTO_NORMATIVO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_DOCUMENTO_NORMATIVO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_ELA_AUT_PROYECTO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_ELA_AUT_PROYECTO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_ENLACE_PRO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_ENLACE_PRO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_ENTIDAD
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_ENTIDAD"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_ENTIDAD_FEDERATIVA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_ENTIDAD_FEDERATIVA"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_ESTATUS
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_ESTATUS"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_ESTATUS_CUAPS
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_ESTATUS_CUAPS"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_ESTATUS_RA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_ESTATUS_RA"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_EVALUACIONES
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_EVALUACIONES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_FOCALIZACION
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_FOCALIZACION"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_FONDO_EJERCE_RECURSOS
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_FONDO_EJERCE_RECURSOS"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_FONDOS_ESP_REG_ADH
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_FONDOS_ESP_REG_ADH"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_FONDOS_ESPECIALES
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_FONDOS_ESPECIALES"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_FORMATO_REG_ADM
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_FORMATO_REG_ADM"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_FRECUENCIA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_FRECUENCIA"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_GEORREFERENCIACION
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_GEORREFERENCIACION"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_GRUPO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_GRUPO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_GRUPO_ROL
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_GRUPO_ROL"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_GRUPO_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_GRUPO_USUARIO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_IDENTIFICADOR_EJE_FON
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_IDENTIFICADOR_EJE_FON"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_INCI_PROYECTO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_INCI_PROYECTO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_INDICES
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_INDICES"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_INFO_APORTA_SISI
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_INFO_APORTA_SISI"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_INFO_INTE_ADM
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_INFO_INTE_ADM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_INFORMACION_APO_SISI
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_INFORMACION_APO_SISI"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_INSUMOS_REGISTRO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_INSUMOS_REGISTRO"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_MATRIZ_FOCALIZACION
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_MATRIZ_FOCALIZACION"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_MATRIZ_GESTION
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_MATRIZ_GESTION"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_MENU
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_MENU"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_MIR
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_MIR"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_MUNICIPIO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_MUNICIPIO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_NOMBRE_COLABORADOR
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_NOMBRE_COLABORADOR"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_NORMATIVIDAD_PRO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_NORMATIVIDAD_PRO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_OBJETIVOS_ESP
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_OBJETIVOS_ESP"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_OBJETO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_OBJETO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_ORDEN_DE_GOBIERNO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_ORDEN_DE_GOBIERNO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_ORDEN_GOBIERNO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_ORDEN_GOBIERNO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PADRON
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PADRON"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PANTALLA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PANTALLA"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PART_UA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PART_UA"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PARTICIPANTES
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PARTICIPANTES"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PERIODICIDAD
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PERIODICIDAD"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PROGRAMA_CON_PRO_SISI
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PROGRAMA_CON_PRO_SISI"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PROGRAMA_CUAPS
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PROGRAMA_CUAPS"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PROGRAMA_INF_APO_SISI
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PROGRAMA_INF_APO_SISI"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PROGRAMA_RES_PRO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PROGRAMA_RES_PRO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PROGRAMAS_SOCIALES
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PROGRAMAS_SOCIALES"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PROYECTOS_CAR
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PROYECTOS_CAR"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PROYECTOS_DER_SOC
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PROYECTOS_DER_SOC"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_PROYECTOS_FONDOS
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_PROYECTOS_FONDOS"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_RECURSOS_FINANCIEROS
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_RECURSOS_FINANCIEROS"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_REGISTRO_ADHESION
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_REGISTRO_ADHESION"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_REGISTRO_ADHESION_AUT
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_REGISTRO_ADHESION_AUT"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_REGISTRO_VARIABLES
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_REGISTRO_VARIABLES"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_REGISTROS_ADM
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_REGISTROS_ADM"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_REGISTROS_ADMIN
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_REGISTROS_ADMIN"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_REPRESENTANTE_SEDESOL
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_REPRESENTANTE_SEDESOL"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_RESPONSABLE_FONDO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_RESPONSABLE_FONDO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_RESPONSABLE_PRO_SOC
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_RESPONSABLE_PRO_SOC"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_ROL
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_ROL"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_ROL_MENU
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_ROL_MENU"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TEMATICA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TEMATICA"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TEMATICA_BIE
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TEMATICA_BIE"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TIPO_ADM
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TIPO_ADM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TIPO_APOYO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TIPO_APOYO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TIPO_APOYO_DER
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TIPO_APOYO_DER"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TIPO_APOYO_PRO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TIPO_APOYO_PRO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TIPO_AUTORIZADOR
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TIPO_AUTORIZADOR"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TIPO_COLABORADOR
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TIPO_COLABORADOR"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TIPO_CONVENIO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TIPO_CONVENIO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TIPO_DOCUMENTO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TIPO_DOCUMENTO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TIPO_PADRON
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TIPO_PADRON"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TIPO_PARTICIPACION
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TIPO_PARTICIPACION"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_TITULAR_CONVENIO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_TITULAR_CONVENIO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_UA_SIN_PROGRAMA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_UA_SIN_PROGRAMA"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_UBICACION_GEOGRAFICA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_UBICACION_GEOGRAFICA"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_UNIDAD_ADM
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_UNIDAD_ADM"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_UNIDAD_ADMINISTRATIVA
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_UNIDAD_ADMINISTRATIVA"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_USUARIO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_USUARIO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_USUARIO_ROL
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_USUARIO_ROL"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_VARIABLES_ADM
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_VARIABLES_ADM"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_VERTIENTES
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_VERTIENTES"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 1 CACHE 20 NOORDER  NOCYCLE ;
--------------------------------------------------------
--  DDL for Sequence SEQ_CSC_VIGENCIA_CONVENIO
--------------------------------------------------------

   CREATE SEQUENCE  "SEDESOL"."SEQ_CSC_VIGENCIA_CONVENIO"  MINVALUE 1 MAXVALUE 999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
